### ISSUE TITLE
Newtypes for strings

### ISSUE THREAD

**Issue by paulyoung** [paulyoung/purescript-webidl-ffi#4]
I think this is a good idea but don't have a good intuition for where to do this and where not too.

I imagine there could be things like:
- `ModuleName`
- `WebIDL`
- `PureScript`

and also possibly things like:
- `MemberName`
- `NodeName`
- `NodeTarget`
- `TypeElement`
- `TypeName`
- `TypeFamily`

but generally unsure.

I'm also not clear in which file(s) each of these should be defined.

@paf31 – what did you have in mind?

**Comment by paf31** [comment]
Those sound good. I would just go through the source and extract them one by one. Some is better than none, you don't have to get them all 😄

**Comment by paulyoung** [comment]
That definitely wasn't mean to be an exhaustive list.

Any advice on where to define them? It seems like at least some will need to live in a separate file to avoid circular references.
